name: Actions Lint

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Setup Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff  # v5.5.0
        with:
          go-version: "1.23"

      - name: Install actionlint
        run: |
          mkdir -p "${HOME}/.local/bin"
          echo "${HOME}/.local/bin" >> "$GITHUB_PATH"
          GOBIN="${HOME}/.local/bin" go install github.com/rhysd/actionlint/cmd/actionlint@v1.7.8

      - name: Run actionlint
        run: actionlint -color
